name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.0.1
homepage: https://github.com/impyf104/fl_chart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_drawing: ^0.4.1
  equatable: ^1.2.0
  flustars: ^0.3.2  


dev_dependencies:
  flutter_test:
    sdk: flutter
